### ISSUE TITLE
Can´t edit spaces name in inspector (Sketchup 2022)

### ISSUE THREAD

**Issue by ZeroConsultingUser** [openstudiocoalition/openstudio-sketchup-plugin#104] opened 2022-02-11 07:32 UTC
When I try to edit the name of any space in my model, Sketchup doesn´t recognize the letters, it activates the associated keyboard shortcuts. I only can write the letter wich doesn´t have any associated shortcut. 

![image](https://user-images.githubusercontent.com/74355190/153552446-4ebcc9d1-9e68-470d-9bb5-41033e2e9714.png)

It´s probably I have to deshabilite some configuration. This issue appears in Sketchup 2022.

Thanks!

**Comment by macumber** [comment] 2022-03-07 03:12
I have confirmed this happens to me as well in SketchUp 2022.

**Comment by CoIin** [comment] 2022-03-07 03:42
SketchUp 2022.0.1 has a number of things fixed in it, including this one:

   (Win) Fixed an issue where keyboard input into an extension window would activate shortcuts.

Here is the new version installer: https://www.sketchup.com/sketchup/SketchUpPro-full-exe

**Comment by macumber** [comment] 2022-03-07 04:22
Thanks for the fast reply @CoIin. Unfortunately, the issue is still occurring with the latest release

![2022-03-06_21-20-40](https://user-images.githubusercontent.com/1327850/156967592-958a65a6-6145-4bcc-a8aa-f89946b36fd6.gif)

**Comment by eringold** [comment] 2022-04-21 21:30
>Not sure if this is related to SketchUp 2022 or Windows 11 change

I'm seeing this with Sketchup 22.0.354 on Windows 10

**Comment by macumber** [comment] 2022-07-23 17:03
This issue is being tracked somewhat at https://github.com/SketchUp/api-issue-tracker/issues/607

In the meantime, it is possible to work around this by removing single letter shortcuts under Window->Preferences->Shortcuts.  I have exported a set of shortcuts that can be imported to work around this issue.  Download the file below, rename it to RemoveShortcuts.dat, go to Window->Preferences->Shortcuts and import it.  You may want to export your current shortcuts as a backup first.

[RemoveShortcuts.dat.txt](https://github.com/openstudiocoalition/openstudio-sketchup-plugin/files/9174219/RemoveShortcuts.dat.txt)

**Comment by macumber** [comment] 2022-12-20 17:14
This issue is fixed in SU 2023 preview build SketchUp 23.0.117.  For affected SketchUp versions the workaround to remove single character shortcuts is sufficient.  Closing as won't fix.

**Closed by macumber** 2022-12-20 17:14 UTC
